[workspace]
resolver = "2"

members = [
    "download-cef",
    "update-bindings",
    "sys",
    "cef",
]

[workspace.package]
version = "131.3.4"
edition = "2021"
license = "Apache-2.0 OR MIT"
authors = [
    "Wu Yu Wei <yuweiwu@pm.me>",
    "Bill Avery <wravery@gmail.com>",
    "csmoe <csmoe@msn.com>",
]
repository = "https://github.com/tauri-apps/cef-rs"

[workspace.dependencies]
cef-sys = { package = "libcef-sys", version = "131.3.4", path = "sys" }
download-cef = { version = "1.0.0", path = "download-cef" }
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "2.0"
winit = "0.30"
