[package]
name = "tests_shared"
publish = false

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
sandbox = ["cef/sandbox"]

[dependencies]
cef.workspace = true

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_System_Performance",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
]

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-app-kit = { workspace = true, features = ["NSApplication", "NSResponder"] }
objc2-foundation.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
glib.workspace = true
